# Generated by Django 3.2.16 on 2022-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20221113_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_read',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
